### ISSUE TITLE
Can I boot without lk2nd?

### ISSUE THREAD

**Issue by Mr-Yuling** [msm8953-mainline/linux#187]
I want to boot without lk2nd

**Comment by vipaoL** [comment]
What device and why?
I'm not sure, but the kernel probably will boot if you add some properties like board-id to your dts. And then you'll find the display panel and touch screen not working, because lk2nd helps the kernel to select a proper node for them, you'll need to hardcode your panel driver and the dts node for your touch screen. And you'll need to carry this changes though kernel updates and recompile the kernel each time.
I see no disadvantages in lk2nd

**Comment by barni2000** [comment]
You can but couple of function will be broken, apcs-clocks will not work and performance will be very bad. For display panel you will need to change panel comaptible to work etc.
